import type { Job } from '../types/job'
import { scoreJobs } from './matchingEngine'
import type { JobPreferences } from '../types/preferences'

export function getTodayKey(): string {
    const today = new Date()
    return `jobTrackerDigest_${today.getFullYear()}-${String(today.getMonth() + 1).padStart(2, '0')}-${String(today.getDate()).padStart(2, '0')}`
}

export function loadDigest(key: string): Job[] | null {
    try {
        const stored = localStorage.getItem(key)
        if (stored) return JSON.parse(stored)
    } catch (e) {
        console.error('Failed to load digest', e)
    }
    return null
}

export function saveDigest(key: string, jobs: Job[]): void {
    try {
        localStorage.setItem(key, JSON.stringify(jobs))
    } catch (e) {
        console.error('Failed to save digest', e)
    }
}

export function generateDigest(allJobs: Job[], prefs: JobPreferences, dismissedIds: string[] = []): Job[] {
    const scored = scoreJobs(allJobs, prefs)

    return scored
        .filter(job => {
            // 1. Dismiss Check
            if (dismissedIds.includes(job.id)) return false

            // 2. Threshold Check
            const score = job.matchScore || 0
            if (score < prefs.minMatchScore) return false

            // 3. Safety Check
            return score > 0
        })
        .sort((a, b) => {
            const scoreA = a.matchScore || 0
            const scoreB = b.matchScore || 0
            // Score DESC
            if (scoreB !== scoreA) return scoreB - scoreA
            // Date ASC
            return a.postedDaysAgo - b.postedDaysAgo
        })
        .slice(0, 10)
}

export function formatDigestForClipboard(jobs: Job[]): string {
    const dateStr = new Date().toLocaleDateString(undefined, { weekday: 'long', month: 'long', day: 'numeric' })
    let text = `📅 DAILY JOB DIGEST — ${dateStr}\n\n`

    if (jobs.length === 0) return text + "No matching roles found for today."

    jobs.forEach((job, idx) => {
        text += `${idx + 1}. ${job.title} at ${job.company}\n`
        text += `   📍 ${job.location} (${job.mode}) | 💼 ${job.experience}\n`
        text += `   🔥 ${job.matchScore}% Match\n`
        text += `   🔗 Apply: ${job.applyUrl}\n\n`
    })

    text += `Generated by Job Notification Tracker`
    return text
}

export function formatDigestForEmail(jobs: Job[]): string {
    return encodeURIComponent(formatDigestForClipboard(jobs))
}
